// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	float r = id.x & id.y;
	float g = 0;// (id.x & 15)/15.0;
	float b = 0;//(id.y & 15)/15.0;
	float a = 0.0;

	Result[id.xy] = float4(r, g, b, a);
}
